@registryPort = 62905

GET http://localhost:{{registryPort}}/ HTTP/1.1

###

POST http://localhost:{{registryPort}}/register HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "host": "localhost",
    "port": 8080
}

###

POST http://localhost:{{registryPort}}/register HTTP/1.1
content-type: application/json

{
    "name2": "sample",
    "host": "localhost",
    "port": 8080
}

###

GET http://localhost:{{registryPort}}/sample HTTP/1.1

###

@service = 27a5e014-ebc4-4f18-9f6a-72f4eba6bc6e

POST http://localhost:{{registryPort}}/{{service}} HTTP/1.1

###

DELETE http://localhost:{{registryPort}}/{{service}} HTTP/1.1
