@registryPort = 51270

GET http://localhost:{{registryPort}}/ HTTP/1.1

###

POST http://localhost:{{registryPort}}/register HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "host": "localhost",
    "port": 8080
}

###

@service = e5be69b8-d03a-4b60-8c8a-7c9df59447cb

POST http://localhost:{{registryPort}}/{{service}} HTTP/1.1
